# Lecture 7 : Creating Arrays

In [1]:
import numpy as np

In [3]:
my_list1 = [1,2,3,4]

In [4]:
my_array1 = np.array(my_list1)
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = (11,22,33,44)

In [6]:
my_lists = (my_list1,my_list2)
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [9]:
print my_array2.shape
my_array2.dtype

(2, 4)


dtype('int64')

In [10]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [11]:
my_zeros_array = np.zeros(5)
my_zeros_array.dtype

dtype('float64')

In [12]:
my_ones_array = np.ones([5,5])
my_ones_array

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [13]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [14]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [17]:
print np.arange(5)
np.arange(5,50,2)

[0 1 2 3 4]


array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

# Lecture 8 - Using arrays & scalars